### ISSUE TITLE
Change min sdk

### ISSUE THREAD

**Issue by Zellius** [Zellius/RxLocationManager#7]
Set min sdk to 9

**Comment by nklugman** [comment]
Is there a reason that the min sdk can not be 9? If not, please consider making this improvement.

**Comment by Zellius** [comment]
@nklugman You can try it now

**compile 'com.github.zellius:rxlocationmanager:0.1.2'**
or
**compile 'com.github.zellius:rxlocationmanager.kotlin:0.1.1'**
